-- ============================================================================
-- LIGONINĖS VALDYMO SISTEMA - DDL SCRIPT
-- Oracle APEX 22.1.0
-- Versija: 1.0
-- Data: 2025-12-13
-- ============================================================================
-- Šis scriptas sukuria visas duomenų bazės lenteles su:
-- - Primary Keys
-- - Foreign Keys
-- - Check Constraints
-- - Unique Constraints
-- - Indexes
-- ============================================================================

-- Išvalome esamas lenteles (jei egzistuoja) - atvirkštine priklausomybių tvarka
BEGIN
    FOR t IN (SELECT table_name FROM user_tables
              WHERE table_name IN (
                  'BILLS', 'LAB_TESTS', 'PRESCRIPTIONS', 'PATIENT_DIAGNOSES',
                  'APPOINTMENTS', 'ADMISSIONS', 'DIAGNOSES', 'MEDICATIONS',
                  'BEDS', 'ROOMS', 'NURSES', 'DOCTORS', 'EMPLOYEES',
                  'DEPARTMENTS', 'PATIENTS'
              )) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
END;
/

-- Išvalome sequences
BEGIN
    FOR s IN (SELECT sequence_name FROM user_sequences
              WHERE sequence_name LIKE '%_SEQ') LOOP
        EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.sequence_name;
    END LOOP;
END;
/

-- ============================================================================
-- 1. DEPARTMENTS (Skyriai)
-- ============================================================================
CREATE TABLE departments (
    department_id       NUMBER          GENERATED BY DEFAULT AS IDENTITY,
    department_name     VARCHAR2(100)   NOT NULL,
    description         VARCHAR2(500),
    head_doctor_id      NUMBER,         -- FK bus pridėta vėliau (circular reference)
    phone_number        VARCHAR2(20),
    building            VARCHAR2(50),
    floor_number        NUMBER(2),
    budget              NUMBER(12,2)    DEFAULT 0,
    created_date        DATE            DEFAULT SYSDATE,
    is_active           CHAR(1)         DEFAULT 'Y',
    --
    CONSTRAINT pk_departments PRIMARY KEY (department_id),
    CONSTRAINT uk_dept_name UNIQUE (department_name),
    CONSTRAINT chk_dept_active CHECK (is_active IN ('Y', 'N')),
    CONSTRAINT chk_dept_floor CHECK (floor_number BETWEEN -2 AND 20)
);

CREATE INDEX idx_dept_active ON departments(is_active);

COMMENT ON TABLE departments IS 'Ligoninės skyriai (Kardiologija, Chirurgija, etc.)';
COMMENT ON COLUMN departments.head_doctor_id IS 'Skyriaus vedantysis gydytojas';
COMMENT ON COLUMN departments.budget IS 'Metinis skyriaus biudžetas';

-- ============================================================================
-- 2. EMPLOYEES (Darbuotojai - bazinė lentelė)
-- ============================================================================
CREATE TABLE employees (
    employee_id         NUMBER          GENERATED BY DEFAULT AS IDENTITY,
    first_name          VARCHAR2(50)    NOT NULL,
    last_name           VARCHAR2(50)    NOT NULL,
    date_of_birth       DATE            NOT NULL,
    gender              CHAR(1)         NOT NULL,
    email               VARCHAR2(100)   NOT NULL,
    phone_number        VARCHAR2(20)    NOT NULL,
    address             VARCHAR2(200),
    city                VARCHAR2(50),
    postal_code         VARCHAR2(10),
    hire_date           DATE            DEFAULT SYSDATE,
    employment_status   VARCHAR2(20)    DEFAULT 'ACTIVE',
    salary              NUMBER(10,2),
    created_date        DATE            DEFAULT SYSDATE,
    modified_date       DATE            DEFAULT SYSDATE,
    --
    CONSTRAINT pk_employees PRIMARY KEY (employee_id),
    CONSTRAINT uk_emp_email UNIQUE (email),
    CONSTRAINT chk_emp_gender CHECK (gender IN ('M', 'F', 'O')),
    CONSTRAINT chk_emp_status CHECK (employment_status IN ('ACTIVE', 'ON_LEAVE', 'TERMINATED')),
    CONSTRAINT chk_emp_salary CHECK (salary >= 0)
);

CREATE INDEX idx_emp_name ON employees(last_name, first_name);
CREATE INDEX idx_emp_status ON employees(employment_status);

COMMENT ON TABLE employees IS 'Visi ligoninės darbuotojai (bazinė lentelė)';

-- ============================================================================
-- 3. DOCTORS (Gydytojai)
-- ============================================================================
CREATE TABLE doctors (
    doctor_id               NUMBER          NOT NULL,
    department_id           NUMBER          NOT NULL,
    specialization          VARCHAR2(100)   NOT NULL,
    license_number          VARCHAR2(50)    NOT NULL,
    consultation_fee        NUMBER(8,2)     DEFAULT 0,
    years_of_experience     NUMBER(2)       DEFAULT 0,
    education               VARCHAR2(500),
    available_for_emergency CHAR(1)         DEFAULT 'Y',
    --
    CONSTRAINT pk_doctors PRIMARY KEY (doctor_id),
    CONSTRAINT fk_doc_employee FOREIGN KEY (doctor_id)
        REFERENCES employees(employee_id) ON DELETE CASCADE,
    CONSTRAINT fk_doc_department FOREIGN KEY (department_id)
        REFERENCES departments(department_id),
    CONSTRAINT uk_doc_license UNIQUE (license_number),
    CONSTRAINT chk_doc_emergency CHECK (available_for_emergency IN ('Y', 'N')),
    CONSTRAINT chk_doc_fee CHECK (consultation_fee >= 0),
    CONSTRAINT chk_doc_exp CHECK (years_of_experience >= 0 AND years_of_experience <= 60)
);

CREATE INDEX idx_doc_dept ON doctors(department_id);
CREATE INDEX idx_doc_spec ON doctors(specialization);

COMMENT ON TABLE doctors IS 'Gydytojai (paveldi iš employees)';
COMMENT ON COLUMN doctors.specialization IS 'Kardiologas, Chirurgas, Pediatras, etc.';

-- ============================================================================
-- 4. NURSES (Medicinos seserys)
-- ============================================================================
CREATE TABLE nurses (
    nurse_id            NUMBER          NOT NULL,
    department_id       NUMBER          NOT NULL,
    certification_level VARCHAR2(50)    NOT NULL,
    shift_preference    VARCHAR2(20)    DEFAULT 'DAY',
    license_number      VARCHAR2(50)    NOT NULL,
    --
    CONSTRAINT pk_nurses PRIMARY KEY (nurse_id),
    CONSTRAINT fk_nurse_employee FOREIGN KEY (nurse_id)
        REFERENCES employees(employee_id) ON DELETE CASCADE,
    CONSTRAINT fk_nurse_department FOREIGN KEY (department_id)
        REFERENCES departments(department_id),
    CONSTRAINT uk_nurse_license UNIQUE (license_number),
    CONSTRAINT chk_nurse_shift CHECK (shift_preference IN ('DAY', 'NIGHT', 'ROTATING'))
);

CREATE INDEX idx_nurse_dept ON nurses(department_id);

COMMENT ON TABLE nurses IS 'Medicinos seserys (paveldi iš employees)';

-- Pridedame circular reference DEPARTMENTS -> DOCTORS
ALTER TABLE departments
ADD CONSTRAINT fk_dept_head_doctor
FOREIGN KEY (head_doctor_id) REFERENCES doctors(doctor_id);

CREATE INDEX idx_dept_head ON departments(head_doctor_id);

-- ============================================================================
-- 5. ROOMS (Palatai)
-- ============================================================================
CREATE TABLE rooms (
    room_id         NUMBER          GENERATED BY DEFAULT AS IDENTITY,
    department_id   NUMBER          NOT NULL,
    room_number     VARCHAR2(20)    NOT NULL,
    room_type       VARCHAR2(20)    NOT NULL,
    floor_number    NUMBER(2),
    is_available    CHAR(1)         DEFAULT 'Y',
    daily_rate      NUMBER(8,2)     DEFAULT 0,
    created_date    DATE            DEFAULT SYSDATE,
    --
    CONSTRAINT pk_rooms PRIMARY KEY (room_id),
    CONSTRAINT fk_room_department FOREIGN KEY (department_id)
        REFERENCES departments(department_id) ON DELETE CASCADE,
    CONSTRAINT uk_room_number UNIQUE (room_number),
    CONSTRAINT chk_room_type CHECK (room_type IN ('PRIVATE', 'SEMI_PRIVATE', 'ICU', 'EMERGENCY', 'OPERATING')),
    CONSTRAINT chk_room_available CHECK (is_available IN ('Y', 'N')),
    CONSTRAINT chk_room_rate CHECK (daily_rate >= 0)
);

CREATE INDEX idx_room_dept ON rooms(department_id);
CREATE INDEX idx_room_type ON rooms(room_type);
CREATE INDEX idx_room_available ON rooms(is_available);

COMMENT ON TABLE rooms IS 'Ligoninės palatai';
COMMENT ON COLUMN rooms.room_type IS 'PRIVATE (vienvietė), SEMI_PRIVATE (dvivietė), ICU (intensyvi priežiūra), EMERGENCY, OPERATING (operacinė)';

-- ============================================================================
-- 6. BEDS (Lovos)
-- ============================================================================
CREATE TABLE beds (
    bed_id                  NUMBER          GENERATED BY DEFAULT AS IDENTITY,
    room_id                 NUMBER          NOT NULL,
    bed_number              VARCHAR2(10)    NOT NULL,
    bed_status              VARCHAR2(20)    DEFAULT 'AVAILABLE',
    last_maintenance_date   DATE,
    created_date            DATE            DEFAULT SYSDATE,
    --
    CONSTRAINT pk_beds PRIMARY KEY (bed_id),
    CONSTRAINT fk_bed_room FOREIGN KEY (room_id)
        REFERENCES rooms(room_id) ON DELETE CASCADE,
    CONSTRAINT uk_bed_room_number UNIQUE (room_id, bed_number),
    CONSTRAINT chk_bed_status CHECK (bed_status IN ('AVAILABLE', 'OCCUPIED', 'MAINTENANCE', 'RESERVED'))
);

CREATE INDEX idx_bed_room ON beds(room_id);
CREATE INDEX idx_bed_status ON beds(bed_status);

COMMENT ON TABLE beds IS 'Lovos palatose';
COMMENT ON COLUMN beds.bed_status IS 'AVAILABLE (laisva), OCCUPIED (užimta), MAINTENANCE (remontuojama), RESERVED (rezervuota)';

-- ============================================================================
-- 7. PATIENTS (Pacientai)
-- ============================================================================
CREATE TABLE patients (
    patient_id              NUMBER          GENERATED BY DEFAULT AS IDENTITY,
    first_name              VARCHAR2(50)    NOT NULL,
    last_name               VARCHAR2(50)    NOT NULL,
    date_of_birth           DATE            NOT NULL,
    gender                  CHAR(1)         NOT NULL,
    blood_type              VARCHAR2(5),
    email                   VARCHAR2(100),
    phone_number            VARCHAR2(20)    NOT NULL,
    emergency_contact_name  VARCHAR2(100),
    emergency_contact_phone VARCHAR2(20),
    address                 VARCHAR2(200),
    city                    VARCHAR2(50),
    postal_code             VARCHAR2(10),
    insurance_number        VARCHAR2(50),
    registration_date       DATE            DEFAULT SYSDATE,
    is_active               CHAR(1)         DEFAULT 'Y',
    created_date            DATE            DEFAULT SYSDATE,
    modified_date           DATE            DEFAULT SYSDATE,
    --
    CONSTRAINT pk_patients PRIMARY KEY (patient_id),
    CONSTRAINT chk_pat_gender CHECK (gender IN ('M', 'F', 'O')),
    CONSTRAINT chk_pat_blood CHECK (blood_type IN ('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-', NULL)),
    CONSTRAINT chk_pat_active CHECK (is_active IN ('Y', 'N'))
);

CREATE INDEX idx_pat_name ON patients(last_name, first_name);
CREATE INDEX idx_pat_insurance ON patients(insurance_number);
CREATE INDEX idx_pat_regdate ON patients(registration_date);
CREATE INDEX idx_pat_active ON patients(is_active);

COMMENT ON TABLE patients IS 'Pacientų registras';
COMMENT ON COLUMN patients.blood_type IS 'Kraujo grupė';
COMMENT ON COLUMN patients.insurance_number IS 'Sveikatos draudimo numeris';

-- ============================================================================
-- 8. APPOINTMENTS (Vizitai/Konsultacijos)
-- ============================================================================
CREATE TABLE appointments (
    appointment_id      NUMBER          GENERATED BY DEFAULT AS IDENTITY,
    patient_id          NUMBER          NOT NULL,
    doctor_id           NUMBER          NOT NULL,
    appointment_date    DATE            NOT NULL,
    appointment_time    VARCHAR2(5)     NOT NULL, -- HH24:MI formatas
    duration_minutes    NUMBER(3)       DEFAULT 30,
    appointment_type    VARCHAR2(20)    DEFAULT 'CONSULTATION',
    status              VARCHAR2(20)    DEFAULT 'SCHEDULED',
    notes               VARCHAR2(1000),
    cancellation_reason VARCHAR2(500),
    created_date        DATE            DEFAULT SYSDATE,
    modified_date       DATE            DEFAULT SYSDATE,
    --
    CONSTRAINT pk_appointments PRIMARY KEY (appointment_id),
    CONSTRAINT fk_appt_patient FOREIGN KEY (patient_id)
        REFERENCES patients(patient_id) ON DELETE CASCADE,
    CONSTRAINT fk_appt_doctor FOREIGN KEY (doctor_id)
        REFERENCES doctors(doctor_id),
    CONSTRAINT chk_appt_type CHECK (appointment_type IN ('CHECKUP', 'CONSULTATION', 'FOLLOWUP', 'EMERGENCY')),
    CONSTRAINT chk_appt_status CHECK (status IN ('SCHEDULED', 'CONFIRMED', 'COMPLETED', 'CANCELLED', 'NO_SHOW')),
    CONSTRAINT chk_appt_duration CHECK (duration_minutes BETWEEN 15 AND 240)
);

CREATE INDEX idx_appt_patient ON appointments(patient_id);
CREATE INDEX idx_appt_doctor ON appointments(doctor_id);
CREATE INDEX idx_appt_date ON appointments(appointment_date);
CREATE INDEX idx_appt_status ON appointments(status);
CREATE INDEX idx_appt_doc_date ON appointments(doctor_id, appointment_date);

COMMENT ON TABLE appointments IS 'Pacientų vizitai pas gydytojus';
COMMENT ON COLUMN appointments.appointment_time IS 'Vizito laikas formatu HH24:MI (pvz., 14:30)';

-- ============================================================================
-- 9. ADMISSIONS (Priėmimai/Hospitalizacija)
-- ============================================================================
CREATE TABLE admissions (
    admission_id        NUMBER          GENERATED BY DEFAULT AS IDENTITY,
    patient_id          NUMBER          NOT NULL,
    bed_id              NUMBER          NOT NULL,
    admitting_doctor_id NUMBER          NOT NULL,
    admission_date      DATE            DEFAULT SYSDATE,
    discharge_date      DATE,
    admission_type      VARCHAR2(20)    DEFAULT 'PLANNED',
    admission_reason    VARCHAR2(500),
    discharge_notes     VARCHAR2(1000),
    status              VARCHAR2(20)    DEFAULT 'ADMITTED',
    created_date        DATE            DEFAULT SYSDATE,
    modified_date       DATE            DEFAULT SYSDATE,
    --
    CONSTRAINT pk_admissions PRIMARY KEY (admission_id),
    CONSTRAINT fk_adm_patient FOREIGN KEY (patient_id)
        REFERENCES patients(patient_id) ON DELETE CASCADE,
    CONSTRAINT fk_adm_bed FOREIGN KEY (bed_id)
        REFERENCES beds(bed_id),
    CONSTRAINT fk_adm_doctor FOREIGN KEY (admitting_doctor_id)
        REFERENCES doctors(doctor_id),
    CONSTRAINT chk_adm_type CHECK (admission_type IN ('EMERGENCY', 'PLANNED', 'TRANSFER')),
    CONSTRAINT chk_adm_status CHECK (status IN ('ADMITTED', 'DISCHARGED', 'TRANSFERRED')),
    CONSTRAINT chk_adm_dates CHECK (discharge_date IS NULL OR discharge_date >= admission_date)
);

CREATE INDEX idx_adm_patient ON admissions(patient_id);
CREATE INDEX idx_adm_bed ON admissions(bed_id);
CREATE INDEX idx_adm_doctor ON admissions(admitting_doctor_id);
CREATE INDEX idx_adm_date ON admissions(admission_date);
CREATE INDEX idx_adm_status ON admissions(status);

COMMENT ON TABLE admissions IS 'Pacientų priėmimai į ligoninę ir išrašymai';
COMMENT ON COLUMN admissions.admission_type IS 'EMERGENCY (skubaus), PLANNED (planuotas), TRANSFER (iš kito skyriaus)';

-- ============================================================================
-- 10. DIAGNOSES (Diagnozių katalogas)
-- ============================================================================
CREATE TABLE diagnoses (
    diagnosis_id    NUMBER          GENERATED BY DEFAULT AS IDENTITY,
    diagnosis_code  VARCHAR2(20)    NOT NULL,
    diagnosis_name  VARCHAR2(200)   NOT NULL,
    category        VARCHAR2(100),
    severity_level  VARCHAR2(20),
    description     VARCHAR2(1000),
    is_active       CHAR(1)         DEFAULT 'Y',
    created_date    DATE            DEFAULT SYSDATE,
    --
    CONSTRAINT pk_diagnoses PRIMARY KEY (diagnosis_id),
    CONSTRAINT uk_diag_code UNIQUE (diagnosis_code),
    CONSTRAINT chk_diag_active CHECK (is_active IN ('Y', 'N')),
    CONSTRAINT chk_diag_severity CHECK (severity_level IN ('MILD', 'MODERATE', 'SEVERE', 'CRITICAL', NULL))
);

CREATE INDEX idx_diag_category ON diagnoses(category);
CREATE INDEX idx_diag_active ON diagnoses(is_active);

COMMENT ON TABLE diagnoses IS 'Standartizuotas diagnozių katalogas (panašus į ICD-10)';
COMMENT ON COLUMN diagnoses.diagnosis_code IS 'Unikalus diagnozės kodas (pvz., I21.0 - ūminis transmurinis priekinio miokardo infarktas)';

-- ============================================================================
-- 11. PATIENT_DIAGNOSES (Pacientų diagnozės)
-- ============================================================================
CREATE TABLE patient_diagnoses (
    patient_diagnosis_id    NUMBER          GENERATED BY DEFAULT AS IDENTITY,
    patient_id              NUMBER          NOT NULL,
    diagnosis_id            NUMBER          NOT NULL,
    doctor_id               NUMBER          NOT NULL,
    diagnosis_date          DATE            DEFAULT SYSDATE,
    notes                   VARCHAR2(1000),
    is_primary              CHAR(1)         DEFAULT 'N',
    status                  VARCHAR2(20)    DEFAULT 'ACTIVE',
    created_date            DATE            DEFAULT SYSDATE,
    --
    CONSTRAINT pk_patient_diagnoses PRIMARY KEY (patient_diagnosis_id),
    CONSTRAINT fk_patdiag_patient FOREIGN KEY (patient_id)
        REFERENCES patients(patient_id) ON DELETE CASCADE,
    CONSTRAINT fk_patdiag_diagnosis FOREIGN KEY (diagnosis_id)
        REFERENCES diagnoses(diagnosis_id),
    CONSTRAINT fk_patdiag_doctor FOREIGN KEY (doctor_id)
        REFERENCES doctors(doctor_id),
    CONSTRAINT chk_patdiag_primary CHECK (is_primary IN ('Y', 'N')),
    CONSTRAINT chk_patdiag_status CHECK (status IN ('ACTIVE', 'RESOLVED', 'CHRONIC'))
);

CREATE INDEX idx_patdiag_patient ON patient_diagnoses(patient_id);
CREATE INDEX idx_patdiag_diagnosis ON patient_diagnoses(diagnosis_id);
CREATE INDEX idx_patdiag_doctor ON patient_diagnoses(doctor_id);
CREATE INDEX idx_patdiag_date ON patient_diagnoses(diagnosis_date);

COMMENT ON TABLE patient_diagnoses IS 'Pacientams priskirtos diagnozės';
COMMENT ON COLUMN patient_diagnoses.is_primary IS 'Ar tai pagrindinė diagnozė';
COMMENT ON COLUMN patient_diagnoses.status IS 'ACTIVE (aktyvi), RESOLVED (išspręsta), CHRONIC (lėtinė)';

-- ============================================================================
-- 12. MEDICATIONS (Vaistų katalogas)
-- ============================================================================
CREATE TABLE medications (
    medication_id       NUMBER          GENERATED BY DEFAULT AS IDENTITY,
    medication_name     VARCHAR2(200)   NOT NULL,
    generic_name        VARCHAR2(200),
    manufacturer        VARCHAR2(100),
    category            VARCHAR2(100),
    unit_price          NUMBER(10,2)    DEFAULT 0,
    stock_quantity      NUMBER(10)      DEFAULT 0,
    minimum_stock_level NUMBER(10)      DEFAULT 10,
    dosage_form         VARCHAR2(20)    DEFAULT 'TABLET',
    strength            VARCHAR2(50),
    requires_prescription CHAR(1)       DEFAULT 'Y',
    is_available        CHAR(1)         DEFAULT 'Y',
    created_date        DATE            DEFAULT SYSDATE,
    modified_date       DATE            DEFAULT SYSDATE,
    --
    CONSTRAINT pk_medications PRIMARY KEY (medication_id),
    CONSTRAINT uk_med_name UNIQUE (medication_name, strength),
    CONSTRAINT chk_med_form CHECK (dosage_form IN ('TABLET', 'CAPSULE', 'INJECTION', 'SYRUP', 'CREAM', 'DROPS', 'INHALER')),
    CONSTRAINT chk_med_prescription CHECK (requires_prescription IN ('Y', 'N')),
    CONSTRAINT chk_med_available CHECK (is_available IN ('Y', 'N')),
    CONSTRAINT chk_med_price CHECK (unit_price >= 0),
    CONSTRAINT chk_med_stock CHECK (stock_quantity >= 0)
);

CREATE INDEX idx_med_name ON medications(medication_name);
CREATE INDEX idx_med_category ON medications(category);
CREATE INDEX idx_med_stock ON medications(stock_quantity);
CREATE INDEX idx_med_available ON medications(is_available);

COMMENT ON TABLE medications IS 'Ligoninėje naudojamų vaistų katalogas';
COMMENT ON COLUMN medications.strength IS 'Vaisto stiprumas (pvz., 500mg, 10ml, etc.)';
COMMENT ON COLUMN medications.dosage_form IS 'Forma: tabletė, kapsulė, injekcija, sirupas, etc.';

-- ============================================================================
-- 13. PRESCRIPTIONS (Receptai)
-- ============================================================================
CREATE TABLE prescriptions (
    prescription_id     NUMBER          GENERATED BY DEFAULT AS IDENTITY,
    patient_id          NUMBER          NOT NULL,
    doctor_id           NUMBER          NOT NULL,
    medication_id       NUMBER          NOT NULL,
    prescription_date   DATE            DEFAULT SYSDATE,
    dosage              VARCHAR2(100)   NOT NULL,
    frequency           VARCHAR2(100)   NOT NULL,
    duration_days       NUMBER(3)       NOT NULL,
    quantity            NUMBER(5)       NOT NULL,
    refills_allowed     NUMBER(2)       DEFAULT 0,
    instructions        VARCHAR2(500),
    status              VARCHAR2(20)    DEFAULT 'ACTIVE',
    created_date        DATE            DEFAULT SYSDATE,
    modified_date       DATE            DEFAULT SYSDATE,
    --
    CONSTRAINT pk_prescriptions PRIMARY KEY (prescription_id),
    CONSTRAINT fk_presc_patient FOREIGN KEY (patient_id)
        REFERENCES patients(patient_id) ON DELETE CASCADE,
    CONSTRAINT fk_presc_doctor FOREIGN KEY (doctor_id)
        REFERENCES doctors(doctor_id),
    CONSTRAINT fk_presc_medication FOREIGN KEY (medication_id)
        REFERENCES medications(medication_id),
    CONSTRAINT chk_presc_status CHECK (status IN ('ACTIVE', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT chk_presc_duration CHECK (duration_days > 0 AND duration_days <= 365),
    CONSTRAINT chk_presc_quantity CHECK (quantity > 0),
    CONSTRAINT chk_presc_refills CHECK (refills_allowed >= 0 AND refills_allowed <= 12)
);

CREATE INDEX idx_presc_patient ON prescriptions(patient_id);
CREATE INDEX idx_presc_doctor ON prescriptions(doctor_id);
CREATE INDEX idx_presc_medication ON prescriptions(medication_id);
CREATE INDEX idx_presc_date ON prescriptions(prescription_date);
CREATE INDEX idx_presc_status ON prescriptions(status);

COMMENT ON TABLE prescriptions IS 'Gydytojų išrašyti receptai pacientams';
COMMENT ON COLUMN prescriptions.dosage IS 'Dozavimas (pvz., 500mg)';
COMMENT ON COLUMN prescriptions.frequency IS 'Dažnumas (pvz., 2 kartus per dieną)';
COMMENT ON COLUMN prescriptions.duration_days IS 'Vartojimo trukmė dienomis';

-- ============================================================================
-- 14. LAB_TESTS (Laboratoriniai tyrimai)
-- ============================================================================
CREATE TABLE lab_tests (
    lab_test_id         NUMBER          GENERATED BY DEFAULT AS IDENTITY,
    patient_id          NUMBER          NOT NULL,
    doctor_id           NUMBER          NOT NULL,
    test_type           VARCHAR2(50)    NOT NULL,
    test_date           DATE            NOT NULL,
    test_time           VARCHAR2(5),
    status              VARCHAR2(20)    DEFAULT 'ORDERED',
    results             CLOB,
    normal_range        VARCHAR2(200),
    lab_technician_name VARCHAR2(100),
    cost                NUMBER(10,2)    DEFAULT 0,
    notes               VARCHAR2(1000),
    created_date        DATE            DEFAULT SYSDATE,
    modified_date       DATE            DEFAULT SYSDATE,
    --
    CONSTRAINT pk_lab_tests PRIMARY KEY (lab_test_id),
    CONSTRAINT fk_lab_patient FOREIGN KEY (patient_id)
        REFERENCES patients(patient_id) ON DELETE CASCADE,
    CONSTRAINT fk_lab_doctor FOREIGN KEY (doctor_id)
        REFERENCES doctors(doctor_id),
    CONSTRAINT chk_lab_type CHECK (test_type IN ('BLOOD', 'URINE', 'XRAY', 'MRI', 'CT_SCAN', 'ULTRASOUND', 'ECG', 'EEG', 'BIOPSY')),
    CONSTRAINT chk_lab_status CHECK (status IN ('ORDERED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT chk_lab_cost CHECK (cost >= 0)
);

CREATE INDEX idx_lab_patient ON lab_tests(patient_id);
CREATE INDEX idx_lab_doctor ON lab_tests(doctor_id);
CREATE INDEX idx_lab_date ON lab_tests(test_date);
CREATE INDEX idx_lab_status ON lab_tests(status);
CREATE INDEX idx_lab_type ON lab_tests(test_type);

COMMENT ON TABLE lab_tests IS 'Pacientams atliekami laboratoriniai tyrimai';
COMMENT ON COLUMN lab_tests.test_type IS 'BLOOD (kraujo tyrimas), URINE (šlapimo), XRAY (rentgenas), MRI, CT_SCAN, ULTRASOUND (echoskopija), ECG (elektrokardiograma), etc.';
COMMENT ON COLUMN lab_tests.results IS 'CLOB laukas dideliems rezultatams (gali būti JSON ar XML formatu)';

-- ============================================================================
-- 15. BILLS (Sąskaitos)
-- ============================================================================
CREATE TABLE bills (
    bill_id         NUMBER          GENERATED BY DEFAULT AS IDENTITY,
    patient_id      NUMBER          NOT NULL,
    admission_id    NUMBER,         -- gali būti NULL jei sąskaita už vizitą
    appointment_id  NUMBER,         -- gali būti NULL jei sąskaita už priėmimą
    bill_date       DATE            DEFAULT SYSDATE,
    due_date        DATE            NOT NULL,
    total_amount    NUMBER(12,2)    DEFAULT 0,
    paid_amount     NUMBER(12,2)    DEFAULT 0,
    balance         NUMBER(12,2)    GENERATED ALWAYS AS (total_amount - paid_amount) VIRTUAL,
    payment_status  VARCHAR2(20)    DEFAULT 'UNPAID',
    payment_method  VARCHAR2(20),
    payment_date    DATE,
    discount_percent NUMBER(5,2)   DEFAULT 0,
    tax_amount      NUMBER(10,2)    DEFAULT 0,
    notes           VARCHAR2(500),
    created_date    DATE            DEFAULT SYSDATE,
    modified_date   DATE            DEFAULT SYSDATE,
    --
    CONSTRAINT pk_bills PRIMARY KEY (bill_id),
    CONSTRAINT fk_bill_patient FOREIGN KEY (patient_id)
        REFERENCES patients(patient_id) ON DELETE CASCADE,
    CONSTRAINT fk_bill_admission FOREIGN KEY (admission_id)
        REFERENCES admissions(admission_id) ON DELETE SET NULL,
    CONSTRAINT fk_bill_appointment FOREIGN KEY (appointment_id)
        REFERENCES appointments(appointment_id) ON DELETE SET NULL,
    CONSTRAINT chk_bill_status CHECK (payment_status IN ('UNPAID', 'PARTIAL', 'PAID', 'OVERDUE')),
    CONSTRAINT chk_bill_method CHECK (payment_method IN ('CASH', 'CARD', 'INSURANCE', 'BANK_TRANSFER', NULL)),
    CONSTRAINT chk_bill_amounts CHECK (paid_amount <= total_amount),
    CONSTRAINT chk_bill_total CHECK (total_amount >= 0),
    CONSTRAINT chk_bill_paid CHECK (paid_amount >= 0),
    CONSTRAINT chk_bill_discount CHECK (discount_percent >= 0 AND discount_percent <= 100),
    CONSTRAINT chk_bill_dates CHECK (due_date >= bill_date),
    CONSTRAINT chk_bill_source CHECK (NOT (admission_id IS NOT NULL AND appointment_id IS NOT NULL))
);

CREATE INDEX idx_bill_patient ON bills(patient_id);
CREATE INDEX idx_bill_admission ON bills(admission_id);
CREATE INDEX idx_bill_appointment ON bills(appointment_id);
CREATE INDEX idx_bill_date ON bills(bill_date);
CREATE INDEX idx_bill_status ON bills(payment_status);
CREATE INDEX idx_bill_due ON bills(due_date);

COMMENT ON TABLE bills IS 'Pacientų sąskaitos už suteiktas paslaugas';
COMMENT ON COLUMN bills.balance IS 'Virtual column: automatiškai skaičiuojama kaip total_amount - paid_amount';
COMMENT ON COLUMN bills.admission_id IS 'Sąskaita už hospitalizaciją (jei taikoma)';
COMMENT ON COLUMN bills.appointment_id IS 'Sąskaita už vizitą (jei taikoma)';

-- ============================================================================
-- PABAIGA: Lentelės sėkmingai sukurtos
-- ============================================================================

-- Informacija apie sukurtas lenteles
SELECT 'Sukurta ' || COUNT(*) || ' lentelių' AS info
  FROM user_tables
 WHERE table_name IN (
    'BILLS', 'LAB_TESTS', 'PRESCRIPTIONS', 'PATIENT_DIAGNOSES',
    'APPOINTMENTS', 'ADMISSIONS', 'DIAGNOSES', 'MEDICATIONS',
    'BEDS', 'ROOMS', 'NURSES', 'DOCTORS', 'EMPLOYEES',
    'DEPARTMENTS', 'PATIENTS'
);

-- Informacija apie sukurtus indexus
SELECT 'Sukurta ' || COUNT(*) || ' indeksų' AS info
  FROM user_indexes
 WHERE table_name IN (
    'BILLS', 'LAB_TESTS', 'PRESCRIPTIONS', 'PATIENT_DIAGNOSES',
    'APPOINTMENTS', 'ADMISSIONS', 'DIAGNOSES', 'MEDICATIONS',
    'BEDS', 'ROOMS', 'NURSES', 'DOCTORS', 'EMPLOYEES',
    'DEPARTMENTS', 'PATIENTS'
)
   AND index_name NOT LIKE 'SYS_%';

COMMIT;
